sudo: false

language: node_js
node_js:
  - stable

# before_install:
# - npm install codecov.io coveralls

# after_success:
# - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
# - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
# - yarn build

script:
  - yarn build
